### PR TITLE
fix: tsconfig

### LINKED ISSUE #426: useFormTable ajax请求报没有finally函数的异常 antdpro2.2.1
TypeError: this.service.apply(...).then(...).catch(...).finally is not a function

### LINKED ISSUE #486: useRequest need tslib bug
image

### PR DESCRIPTION
**Pull request by awmleer**
- change build target from `ES6` to `ES5`
- remove `importHelpers`

Close #486 
Close #426

### CODE REVIEW

File: packages/hooks/src/useDrop/useDrop.ts [hunk 1]
```diff
@@ -65,7 +65,7 @@ const useDrop = (options: DropAreaOptions = {}): [DropProps, DropAreaState] => {
       }
 
       if (dataTransfer.files && dataTransfer.files.length && optionsRef.current.onFiles) {
-        optionsRef.current.onFiles([...dataTransfer.files], event as React.DragEvent);
+        optionsRef.current.onFiles([...Array.from(dataTransfer.files)], event as React.DragEvent);
```
Comment (brickspert) [inline packages/hooks/src/useDrop/useDrop.ts]:
```suggestion
        optionsRef.current.onFiles(Array.from(dataTransfer.files), event as React.DragEvent);
```

**Review by brickspert — APPROVED** [review]
LGTM
