### PR TITLE
fix: prevent useRequest run.then when canceled

### LINKED ISSUE #905: useRequest被取消成功后为什么不抛出类似axios的错误
```JavaScript
 // 案例1： 当前路径 /index
  function testPromise() {
    return new Promise((resolve, reject) => {
      reject(new Error('test error'));
    });
  }
  const { run: runTest } = useRequest(testPromise, {
    manual: true,
    throwOnError: true,
  });
  useEffect(() => {
    runTest()
      .then((result) => {
        console.log('🚀 ~ testPromise 62 ~ runTest ~ result', result);
      })
      .catch((err) => {
        console.log('🚀 ~ testPromise 65 ~ runTest ~ err', err);
      });
    history.push('/user/login');
    // 跳转路由后的执行结果: testPromise 62 ~ runTest ~ result undefined
    // useRequest在组件卸载时进行了unmount cancel unsubscribe，
    // cancel后为什么不抛出 new Error('Operation canceled')之类的错误，而是直接Promise.resolve(). 
     @ps:这里只是猜测是cancel操作后返回了结果，不太懂哈
    // cancel成功后不抛出错误，导致进入业务逻辑不符合预期
  });

  // 案例2：
  function testPromise2() {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        reject(new Error('test error'));
      }, 2000);
    });
  }
  const { run: runTest2 } = useRequest(testPromise2, {
    manual: true,
    throwOnError: true,
  });
  useEffect(() => {
    runTest2()
      .then((result) => {
        console.log('🚀 ~ file: index.tsx ~ line 119 ~ .then ~ result', result);
      })
      .catch((err) => {
        console.log('🚀 ~ file: index.tsx ~ line 123 ~ useEffect ~ err', err);
      });

    runTest2()
      .then((result) => {
        console.log('🚀 ~ file: index.tsx ~ line 129 ~ .then ~ result', result);
      })
      .catch((err) => {
        console.log('🚀 ~ file: index.tsx ~ line 133 ~ useEffect ~ err', err);
      });
    // 输出：
    // 🚀 ~ file: index.tsx ~ line 119 ~ .then ~ result undefined
    // 🚀 ~ file: index.tsx ~ line 133 ~ useEffect ~ err Error: test error
    // 上一个请求为什么进入了Promise.resolve()而不是抛错
    // 不抛出error会对业务有影响
  }, []);
```

cancel之类的操作是前端操作，肯定能执行成功。期望取消之类的promise状态结果为reject与axios类似
或者提供接口更改取消之类的响应结果

### PR DESCRIPTION
**Pull request by brickspert**
fix: #905

### CODE REVIEW

File: packages/use-request/src/useAsync.ts [hunk 1]
```diff
@@ -148,6 +148,8 @@ class Fetch<R, P extends any[]> {
           }
           return formattedResult;
         }
+        // prevent run.then when request is canceled
+        return new Promise(() => {});
```
Comment (awmleer) [inline packages/use-request/src/useAsync.ts]:
```
if (this.unmountedFlag || currentCount !== this.count) {
  // prevent run.then when request is canceled
  return new Promise(() => {});
}
```

**Review by awmleer — CHANGES_REQUESTED** [review]

**Review by awmleer — APPROVED** [review]
LGTM
