### PR TITLE
fix(useReactive): cannot set a object with read-only and non-configurable property

### LINKED ISSUE #1317: useReactive - read-only and non-configurable data property
ahooks v2.10.12
can't access to record.rule it will showing error like picture below other wise like record.id is working fine. thanks you
Screen Shot 2021-11-20 at 2 53 54 PM
Screen Shot 2021-11-20 at 2 54 21 PM

### PR DESCRIPTION
**Pull request by liuyib**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix: https://github.com/alibaba/hooks/issues/1317

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: packages/hooks/src/useReactive/index.ts [hunk 1]
```diff
@@ -26,6 +26,12 @@ function observer<T extends Record<string, any>>(initialVal: T, cb: () => void):
     get(target, key, receiver) {
       const res = Reflect.get(target, key, receiver);
 
+      // https://github.com/alibaba/hooks/issues/1317
+      const descriptor = Reflect.getOwnPropertyDescriptor(target, key);
+      if (descriptor && descriptor.configurable === false && descriptor.writable === false) {
```
Comment (crazylxr) [inline packages/hooks/src/useReactive/index.ts]: 这行代码改成这样  if (!descriptor.configurable  && !descriptor.writable)会不会优雅一点

Comment (liuyib) [reply packages/hooks/src/useReactive/index.ts]: 我优化下

Comment (liuyib) [reply packages/hooks/src/useReactive/index.ts]: `Reflect.getOwnPropertyDescriptor` 的返回值可能为空，在你推荐的基础上加了可选链，见哥再看下呢
