### PR TITLE
fix: useDebounce 在小程序里使用问题

### LINKED ISSUE #1448: taro中使用防抖节流会报错
image
image

### LINKED ISSUE #2192: 使用Taro开发支付宝小程序，无法使用ahooks
使用Taro开发**支付宝小程序**，使用useRequest中会使用Date.now()，然而代码中是先获取root，然后使用root.Date.now()，导致报错，因为支付宝小程序中 root = {} 就是一个空对象，希望早日解决
image

### PR DESCRIPTION
**Pull request by crazylxr**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix: https://github.com/alibaba/hooks/issues/2192

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

File: packages/hooks/src/utils/lodash-polyfill.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import debounce from 'lodash/debounce';
+
+function isNodeOrWeb() {
```
Comment (brickspert) [inline packages/hooks/src/utils/lodash-polyfill.ts:3]:
```
if(!global.Date) {
  global.Date = Date
}
```

如果是上面这样呢？会有啥区别？

https://github.com/NervJS/taro/issues/8098#issuecomment-731915642

Comment (crazylxr) [reply packages/hooks/src/utils/lodash-polyfill.ts:3]: 感觉跟这个处理方法是一样的，都是为了把 原生对象挂到 global 里

File: packages/hooks/src/utils/lodash-polyfill.ts [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+    global &&
+    global.Object === Object &&
+    global;
+  var freeSelf = typeof self == 'object' && self && self.Object === Object && self;
+  return freeGlobal || freeSelf;
+}
+
+if (!isNodeOrWeb()) {
+  global.Date = Date;
+}
```
Comment (liuyib) [inline packages/hooks/src/utils/lodash-polyfill.ts:15]: 这里需不需要按照：https://github.com/NervJS/taro/issues/8098#issuecomment-731915642, 把用到的全局对象都处理一遍呀？要不然某个 lodash 函数缺哪一个全局变量也不清楚，还需要核对下。

Comment (crazylxr) [reply packages/hooks/src/utils/lodash-polyfill.ts:15]: 我觉得还是按需比较好。 毕竟 taro 只管小程序环境就行了。而我们要兼容小程序、Node、浏览器

**Comment by hchlq** [comment]
这个啥时候合进去呢
