### PR TITLE
fix(useReactive): allow the field value of initialState to be a special object

### LINKED ISSUE #1024: useReactive can't set formData to state
```tsx

const state = useReactive({
logoFormData: undefined
})
const [logoForm, setLogoForm]= useState(undefined)

// I want upload later so I just save formData to state
   state.logoFormData = formData;
  setLogoForm(formData)
  
  // call api service
  - run api upload ==> runUpload(state.logoFormData) not working it become object like picture 1
  - run api upload ==> runUpload(logoForm)  working see picture 2
```

# picture1 useReactive
Screen Shot 2021-07-11 at 2 19 01 PM

# picture 2 useState
Screen Shot 2021-07-11 at 2 22 00 PM

### LINKED ISSUE #2080: useReactive 关于 RegExp 的bug
用例如下：

```js

const a = useReactive({
  b: /123/
})

a.b.test('321')
```

此时浏览器就会报错
`Uncaught TypeError: Method RegExp.prototype.exec called on incompatible receiver [object RegExp]`

目前拿到的 `a.b` 是一个被 `Proxy` 包裹的 `RegExp` ，在后续的使用中造成了麻烦，希望可以在 `get` 时增加一些类型判断，在必要时返回原始类型的数据。

🫡🫡🫡

### PR DESCRIPTION
**Pull request by liuyib**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [x] Site / documentation update
- [x] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close: https://github.com/alibaba/hooks/issues/2080
close: https://github.com/alibaba/hooks/issues/1024

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     allow the field value of initialState to be a special object      |
| 🇨🇳 Chinese |     允许 initialState 的字段值为一个特殊的 JS 对象      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by liuyib** [comment]
@crazylxr  ~~ready for review~~

File: packages/hooks/src/useReactive/index.ts [hunk 1]
```diff
@@ -25,7 +25,9 @@ function observer<T extends Record<string, any>>(initialVal: T, cb: () => void):
   const proxy = new Proxy<T>(initialVal, {
     get(target, key, receiver) {
       const res = Reflect.get(target, key, receiver);
-      return isObject(res) ? observer(res, cb) : res;
+      const isReactElement = isValidElement(res);
```
Comment (luo3house) [inline packages/hooks/src/useReactive/index.ts]: It might not be the issue of React Element since its `_store` is just set to non-writable and non-configurable.

But this reproduction below still throws. So I suggest following the error to make a workaround for accessing objects which are non configurable and readonly above.

```tsx
const NonConfigurableObject = function createNonProxyableObject(): {user: {name: string}} {
  const obj = {}
  Reflect.defineProperty(obj, 'user', { 
    value: { name: "Alice" }, 
    writable: false, 
    configurable: false,
  })
  // Reflect.getOwnPropertyDescriptor(obj, 'user')
  // { value: {…}, writable: false, enumerable: true, configurable: false }
  return obj as any
}();

export default () => {
  const state = useReactive(NonConfigurableObject);

  return (
    <div>
      <div>{state.user.name}</div>
    </div>
  );
};
```

Comment (liuyib) [reply packages/hooks/src/useReactive/index.ts]: Yeh, I realize this, so I am working on it  :)

Comment (liuyib) [reply packages/hooks/src/useReactive/index.ts]: This situation may not be resolved temporarily, so this PR is used to solve other related issue: https://github.com/alibaba/hooks/issues/2080

Comment (liuyib) [reply packages/hooks/src/useReactive/index.ts]: For the problem of "non-writable and non-configurable", I've tried a lot of methods, but no matter which method, there are always some details that cannot be processed.

The best method I've tried is "clone the initialState deeply", example:

```ts
import { cloneDeepWith } from 'lodash';

function deepClone<S>(initialState: S): S {
  const copy = cloneDeepWith(initialState, (value) => {
    const ret = {};

    for (const key of Reflect.ownKeys(value)) {
      ret[key] = Reflect.get(value, key);
    }

    return ret;
  });

  return copy;
}
```

The code above can handles most situations, expect for the "getter/setter + this" in the prototype:

```ts
const parent: Record<string, string> = {
    name: 'parent',
    get value() {
      return this.name;
    },
  };

  const child: Record<string, string> = {
    name: 'child',
  };

  const { result } = renderHook(() => useReactive(parent));
  const proxy = result.current;

  Object.setPrototypeOf(child, proxy);

  expect(child.value).toBe('child');
  expect(proxy.value).toBe('parent');
  expect(parent.value).toBe('parent');

  act(() => delete child.name);
  expect(child.value).toBe('parent');
  expect(proxy.value).toBe('parent');
  expect(parent.value).toBe('parent');

  act(() => delete proxy.name);
  expect(child.value).toBeUndefined();
  expect(proxy.value).toBeUndefined();
  expect(parent.value).toBeUndefined();
```

The above test case fails.

Finally, I gave up trying and haven't find any perfect way.

**Comment by liuyib** [comment]
@crazylxr  ready for review.

**Review by crazylxr — APPROVED** [review]
