### PR TITLE
fix(useMouse): access document in ssr

### LINKED ISSUE #1635: SSR issue with useMouse
I'm using the `useMouse` hook inside a component, within NextJS. but I get the `document is not defined` error on page load. My code is very basic:

```tsx
import {useMouse} from 'ahooks'

export const Hero = () => {
  const mouse = useMouse()

  return (
    <>Mouse {mouse.pageX}</>
)}

```

This happens only when page change/reload. Not with hotreload.

> **Note**
> This is the [link](https://stackblitz.com/edit/nextjs-9mufgi?file=pages%2Findex.js) to reproduce the issue

### PR DESCRIPTION
**Pull request by hchlq**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix #1635

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

File: packages/hooks/src/useMouse/index.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ export default (target?: BasicTarget) => {
       setState(newState);
     },
     {
-      target: document,
+      target: typeof document == 'undefined' ? null : document,
```
Comment (brickspert) [inline packages/hooks/src/useMouse/index.ts]:
```suggestion
      target: () => document,
```

**Review by brickspert — APPROVED** [review]
